version: '3'

services:
  engine-apache:
    image: httpd:2.4-alpine
    container_name: engine-apache
    restart: always
    volumes:
      - /daksha/test-data:/usr/local/apache2/htdocs/
    ports:
      - "8485:80"

  web:
    build: .
    container_name: daksha
    restart: always
    volumes:
      - /daksha/test-data:/daksha/test-data
    ports:
      - "8083:8000"
    environment:
      STORAGE_PATH: "/daksha/test-data"
      APACHE_URL: "http://127.0.0.1:8485/"
      TEST_RESULT_DB: "postgres"
      PG_DB : "postgres"
      PG_USER : "postgres"
      PG_HOST: "postgresdb"
      PG_PASSWORD: "postgres"
      PG_PORT: "5432"
      CRON_ENABLED : "false"
      CRON_FILE_SOURCE : none
      CRON_FILE_PATH : none
  #   #If you want to provide an external Postgres SQL database then remove the below lines .
    depends_on:
      - postgresdb
 
  postgresdb:
    container_name: postgresdb
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /daksha/test-data:/var/lib/postgresql/data
